### ISSUE TITLE
请教下后台人脸识别对比的逻辑是怎样的

### ISSUE THREAD

**Issue by Tipsyume** [shenbengit/JavaCV-FaceDetect#2]
请教下后台人脸识别对比的逻辑是怎样的，不经过服务器，直接在app里实现

**Comment by shenbengit** [comment]
把人脸图片传给后台

**Comment by Tipsyume** [comment]
请教下可以同时检测多人不，并将识别验证的逻辑放到前端App里，不经过后台服务器

**Comment by shenbengit** [comment]
这个只支持人脸检测，支持多人脸检测，识别需要后台服务或者其他三方sdk
